config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: { minimum: 6, maximum: 100}
    validates :description, presence: true, length: { minimum: 10, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    
    def show
        
    end 

    def index 
        @articles = Article.all
    end 

    def new 
        @article = Article.new
    end

    def edit
       
    end

    def create
        @article = Article.new(article_params)
        if @article.save
        flash[:notice] = "Article was created successfully."
        redirect_to @article
        else
        render 'new'
        end
    end

    def update
        if @article.update(params.require(:article).permit(:title, :description))
        flash[:nontice] = "Article was updated successfully"
        redirect_to @article
        else
        render 'edit'
        end
    end
       
    def destroy
        @article.destroy
        redirect_to articles_path
    end
        
 
    private
 
    def set_article
        @article = Article.find(params[:id])
    end
 
    def article_params
        params.require(:article).permit(:title, :description)
    end
 
 end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end
  
    def about
    end
  
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @article, local: true) do |f|%>
<p>
<%= f.label :title %><br>
<%= f.text_field :title %>
</p>

<p>
<%= f.label :description %><br>
<%= f.text_area :description %>
</p>

<p>
<%= f.submit %>
</p>
<% end %>

app/views/articles/edit.html.erb
<h1>EDIT PAGE</h2>

<%= render 'form' %>

<%= link_to 'Cancel and return to articles listing', articles_path %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Browes all Article</h1>

<div class="container">
<% @articles.each do |article| %>
<div class="row justify-content-md-center">
<div class="col-8 mt-4">
  <div class="card text-center shadow mb-5 bg-white rounded">
    <div class="card-header fst-italic">
      by Ryan Locascio
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-danger" %></h5>
      <p class="card-text"><%= truncate(article.description, length: 100) %></p>
      <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
      <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
      <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
    </div>
    <div class="card-footer text-muted">
      <small>Created <%= time_ago_in_words(article.created_at) %> ago,
      edited <%= time_ago_in_words(article.updated_at)%> ago </small>
    </div>
  </div>
  </div>
  </div>
<% end %>
</div>
<%# <table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

   <tbody>
   
  
       <td><%= link_to 'Show', article_path(article) %></td>
        <%# <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <%# <td><%= button_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure?"} %></td>
      <%# </tr>
    %>
  <%# </tbody> %>
<%# </table>  %>

<%# <p> %>
  <%# <%= link_to 'Create new article', new_article_path %> 
<%# </p> %> 

app/views/articles/new.html.erb
<h1>Create new Article</h1>

<%= render 'form' %>

<%= link_to 'Return to articles listing', articles_path %>

app/views/articles/show.html.erb
<h1>Show article details </h1>

<p><strong>Title: </strong><%= @article.title%></p>
<p><strong>Description: </strong><%= @article.description%></p>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %> |
<%= link_to 'Return to articles listing', articles_path %>

app/views/layouts/_messages.html.erb
 <% flash.each do |name, msg| %>
    <%= msg %>
    <% end %>   

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light"> 
    <a id="logo" class="navbar-brand" href="/">The Blog Spot</a> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="/about">About <span class="sr-only"></span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/articles">Articles</a>
        </li>
        <%# <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </li> %>
        <%# <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li> %>
        <%# </ul> %>
        <%# <form class="form-inline my-2 my-md-0">
        <input class="form-control mr-md-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-alert my-2 my-md-0" type="submit">Search</button>
        </form> %>
    </div>
</nav>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# fixed error with line 11 with 'nvm install --lts' which gives you the lates stable version of node%>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
    <%# Font for logo and display text home page %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Comforter+Brush&display=swap" rel="stylesheet">
    <%# Font for navbar about and article %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@1,900&display=swap" rel="stylesheet">
  
  </head>
  
  <body>
      <%= render 'layouts/navigation'%>
      <%= render 'layouts/messages' %>
      <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to the About page</h1>

app/views/pages/home.html.erb
<div class="container" id="home-container">
<div class="jumbotron text-center">
    <h1 class="display-4"> The Blog Spot </h1>
    <p class="lead"> A place to write what you know and feel...</p>
    
    <p>Tell the world a story</p>
    <a class='btn btn-md' href='/articles' role="button"> Browes Articles </a>
</div>
</div>
<div class="container text-center">
<hr>
<small class="text-muted"> &copy 2022; The blog Spot</small>
</div>

<%# <%= link_to 'Articles listing', articles_path %> 
<%# <%= link_to 'About page', about_path %>  